#!/bin/bash

set -e

function nocred {
    echo environment variables aws_id and aws_key must be set with aws credentials
    exit
}

function usage {
    echo "list the files on Amazon's Simple Storage Service
         "
    echo "usage: "$0" [bucketname]
         "
    exit
}

if [ -z "$aws_id" ]; then nocred; fi
if [ -z "$aws_key" ]; then nocred; fi

s3curl.pl --id="$aws_id" --key="$aws_key" -- https://s3.amazonaws.com/"$1"

