#!/bin/bash

set -e

function noacl {
    s3curl.pl --id="$aws_id" --key="$aws_key" --put="$2" -- https://s3.amazonaws.com/"$1"/"$2"
    exit
}

function nocred {
    echo environment variables aws_id and aws_key must be set with aws credentials
    exit
}

function usage {
    echo "put a file onto Amazon's Simple Storage Service
         "
    echo "usage: "$0" bucketname filename [public-read]
         "
    exit
}

if [ -z "$2" ]; then usage; fi
if [ -z "$aws_id" ]; then nocred; fi
if [ -z "$aws_key" ]; then nocred; fi
if [ -z "$3" ]; then noacl "$1" "$2"; fi
if [ ! "$3"='public-read' ]; then usage; fi

s3curl.pl --id="$aws_id" --key="$aws_key" --acl=public-read --put="$2" -- https://s3.amazonaws.com/"$1"/"$2"

